# APPLICATION BASE (ereditato da tutti)
server:
  port: 8090
  session:
    cookie:
      secure: true
  error:
    whitelabel:
      enabled: false
  servlet: 
    context-path: /
  shutdown: graceful

# SPRING BASE   
spring:
  profiles:
    active: h2
  lifecycle:
    timeout-per-shutdown-phase: 40s
  datasource: 
    initialize: false
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# DEFAULT : UTF-8
#  http:
#    encoding:
#      charset: UTF-8
#      enable: true   
#      force: true
  thymeleaf:
    cache: false

# ACTUATOR
management:
# porta senza ssl per gli actuator    
#  server:
#    port: 9090
#    address: 127.0.0.1
#    ssl:
#      enabled: false
  info:
    git: 
      mode: full
  endpoint: 
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "info, health, jolokia, threaddump, scheduledtasks"
        
 # DSS (sostituito rispetto dss.properties)
dss: 
 server:
  signing:
    keystore:
      type: PKCS12
      filename: classpath:user_a_rsa.p12
      password: password
 tsa:
  url: "http://tsa.belgium.be/connect"
 dataloader: 
   ldaptimeoutconnection: 15000
 cachedCRLSource:
   defaultNextUpdateDelay: 180

oj:
  content:
    keystore:
      type: PKCS12
      filename: classpath:keystore.p12
      password: dss-password

current:
  oj:
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.C_.2019.276.01.0001.01.ENG"
  lotl:
    url: "https://ec.europa.eu/tools/lotl/eu-lotl.xml"

lotl:
  country:
    code: EU

cron:
  tl:
    loader:
      enable: true
  initial:
    delay:
      tl:
        loader: 0
  delay:
    tl:
      loader: 3600000
    
default:
  validation:
    policy: "policy/constraint.xml"

proxy:
  http:
    enabled: false
    host: 
    port: 0
    user: 
    password: 
    exclude: 
  https:
    enabled: false
    host: 
    port: 0
    user: 
    password: 
    exclude: 

admin:
  username: admin
  password: admin

tsp-source: "classpath:config/tsp-config.xml"


# EIDAS
# CUSTOM
parer:
  eidas:
    admin-ui:
      enabled: true
      propstoskip: .*H2_USER.*|.*H2_PWD.*|.*ADMIN_USER.*|.*ADMIN_PWD.*|.*user.*|.*password.*|.*email.*      
    validation-ui:
      enabled: true
        
