name: GitHub Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
jobs:
  release:
    uses: RegioneER/parer-github-template/.github/workflows/github-release.yml@v1