name: GitHub Release
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' # every new tag
    branches:
      - master
      - main        
jobs:
  release:
    uses: RegioneER/parer-github-template/.github/workflows/github-release.yml@v1